### PR TITLE
CSS and Class Organization

### PR DESCRIPTION
**Pull request by gmjosack**
- Updated CSS to make dropdown menus more readable
- Deprecated classUuids in favor of groupedClassUuid that allows adding new classes under a group heading.
- Fixed typo on Gutterborn Scum that prevented Stealthy (`itemsm` instead of `items`)
- Use two columns when selecting allowed classes as well for consistency with scvm

classUuids will continue to exist for backwards compatibility and will push everything under Uncategorized

I also removed the sorting and added the classes in the order they appear in their books since they're specified in arrays and maps which maintain their insertion order.

A few unintended formatting changes went in from prettier in the files i touched, let me know if you want those reverted.

### Example of organization
image

### Example working with morkborg-3p
image

### CODE REVIEW

**Comment by gmjosack** [comment]
I used the foundryvtt-cli to dump the databases before/after my pr and this was the only diff

```patch
diff --git a/packs/mork-borg-items/_source/Gutterborn_Scum_gAx8MWLiZcjiWQvc.json b/packs/mork-borg-items/_source/Gutterborn_Scum_gAx8MWLiZcjiWQvc.json
index a968a04..bcf6896 100644
--- a/packs/mork-borg-items/_source/Gutterborn_Scum_gAx8MWLiZcjiWQvc.json
+++ b/packs/mork-borg-items/_source/Gutterborn_Scum_gAx8MWLiZcjiWQvc.json
@@ -14,7 +14,7 @@
     "omenDie": "1d2",
     "startingAgility": "3d6",
     "startingHitPoints": "1d6",
-    "startingItems": "morkborg.mork-borg-itemsm,Stealthy",
+    "startingItems": "morkborg.mork-borg-items,Stealthy",
     "startingPresence": "3d6",
     "startingRolls": "morkborg.mork-borg-tables,Specialities,1\nmorkborg.mork-borg-tables,Bad Birth,1",
     "startingSilver": "1d6*10",
@@ -25,11 +25,11 @@
   "folder": "ltsuj8V60z0lW5wT",
   "_stats": {
     "systemId": "morkborg",
-    "systemVersion": "2.0.0",
-    "coreVersion": "12.325",
+    "systemVersion": "4.0.2",
+    "coreVersion": "12.331",
     "createdTime": 1685213772830,
-    "modifiedTime": 1685232235115,
-    "lastModifiedBy": "LYF9zR8SvB0h2e6R",
+    "modifiedTime": 1726113521540,
+    "lastModifiedBy": "rZwdT0M7uuWLgFbB",
     "compendiumSource": null,
     "duplicateSource": null
   },
   ```

**Comment by mcglincy** [comment]
There's one small wrench with this, which is that the paid heretic module is adding the Shedding vicar to the old-style classUuids list... so it'll show up as Uncategorized and not in Heretic. The next time the module is updated it could deal with that though. FYI @pwatson100

**Review by mcglincy — APPROVED** [review]
LGTM

**Comment by gmjosack** [comment]
Yea I made sure to support classUuids for backwards compat to not break any existing modules but i think having this organization moving forward is very compelling and that module can even push into the existing Heretic group rather than making a new group in the future.

**Comment by gmjosack** [comment]
I also updated the README which coincidentally had an example for adding Shedding Vicar which should have the exact example needed to push it into the Heretic group

**Comment by Murtaza790** [comment]
100644

**Pull request merged**
